
#ifndef THREADSTATE_INCLUDED_H
#define THREADSTATE_INCLUDED_H

enum ThreadState {
	THREAD_STATE_INITIAL,
	THREAD_STATE_RUNNING,
	THREAD_STATE_STOPPING,
	THREAD_STATE_TERMINATED
};

#endif //THREADSTATE_INCLUDED_H
